[package]
name = "cloud-plugin"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[workspace.package]
version = "0.1.0"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bindle = { git = "https://github.com/fermyon/bindle", tag = "v0.8.2", default-features = false, features = [
	"client",
] }
chrono = "0.4"
clap = { version = "3.2.24", features = ["derive", "env"] }
cloud = { path = "crates/cloud" }
cloud-openapi = { git = "https://github.com/fermyon/cloud-openapi", rev = "e007319d3a8ab970c626d6ae3c100240a8d2ee60" }
dirs = "5.0"
tokio = { version = "1.23", features = ["full"] }
tracing = { workspace = true }
rand = "0.8"
reqwest = { version = "0.11", features = ["stream"] }
rpassword = "7.0"
semver = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"
sha2 = "0.10.2"
spin-bindle = { git = "https://github.com/fermyon/spin" }
spin-common = { git = "https://github.com/fermyon/spin" }
spin-loader = { git = "https://github.com/fermyon/spin" }
spin-manifest = { git = "https://github.com/fermyon/spin" }
spin-http = { git = "https://github.com/fermyon/spin" }
spin-trigger-http = { git = "https://github.com/fermyon/spin" }
tempfile = "3.3.0"
url = "2.3"
uuid = { version = "1.3", features = ["v4"] }

[target.'cfg(target_os = "linux")'.dependencies]
# This needs to be an explicit dependency to enable
# '--features openssl/vendored', which is used for Linux releases.
openssl = { version = "0.10" }

[workspace.dependencies]
tracing = { version = "0.1", features = ["log"] }

